/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.liquidaciones;

import dominio.FiadoChofer;
import dominio.Inventario;
import dominio.Liquidacion;
import java.text.DecimalFormat;
import java.text.ParseException;
import javax.swing.JOptionPane;
import sistema.SistemaLiquidaciones;
import sistema.SistemaMantenimiento;
import sistema.SistemaUsuarios;
import ui.usuarios.Constantes;

/**
 *
 * @author Edu
 */
public class VentanaVerSaldoAnteriorLiquidacionNoAcumulativa extends javax.swing.JFrame {

    private final SistemaLiquidaciones sisLiquidaciones;
    private Liquidacion l;
    
    private DecimalFormat df;
    /**
     * Creates new form VentanaVerSaldoAnteriorLiquidacionNoAcumulativa
     */
    public VentanaVerSaldoAnteriorLiquidacionNoAcumulativa(java.awt.Frame parent, boolean modal) {
        //super(parent, modal);
        initComponents();
        sisLiquidaciones = SistemaLiquidaciones.getInstance();
        df = new DecimalFormat("0.00");
        if(!SistemaMantenimiento.getInstance().devolverConfiguracionLiquidacion().isMostrarFiadoClientesCobraChofer()){
            jLabelFiadoChofer.setVisible(false);
            jTextFieldFiadoChofer.setVisible(false);
            jButtonVerFiadoChofer.setVisible(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabelFiadoChofer = new javax.swing.JLabel();
        jTextFieldInventario = new javax.swing.JTextField();
        jTextFieldFiadoChofer = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabelTotal = new javax.swing.JLabel();
        jButtonVerInventario = new javax.swing.JButton();
        jButtonVerFiadoChofer = new javax.swing.JButton();
        jButtonSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Saldo Anterior");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jLabel1.setText("Inventario:");

        jLabelFiadoChofer.setText("Fiado Chofer:");

        jTextFieldInventario.setEditable(false);

        jTextFieldFiadoChofer.setEditable(false);

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 1, 16)); // NOI18N
        jLabel2.setText("Total:");

        jLabelTotal.setFont(new java.awt.Font("Lucida Grande", 1, 16)); // NOI18N
        jLabelTotal.setText("0");

        jButtonVerInventario.setText("Ver Inventario");
        jButtonVerInventario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVerInventarioActionPerformed(evt);
            }
        });

        jButtonVerFiadoChofer.setText("Ver Fiado Chofer");
        jButtonVerFiadoChofer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVerFiadoChoferActionPerformed(evt);
            }
        });

        jButtonSalir.setText("Salir");
        jButtonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(jLabelFiadoChofer)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jTextFieldInventario)
                        .addComponent(jTextFieldFiadoChofer, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabelTotal))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonVerInventario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonVerFiadoChofer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonSalir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextFieldInventario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonVerInventario))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelFiadoChofer)
                    .addComponent(jTextFieldFiadoChofer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonVerFiadoChofer))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(jLabelTotal))
                    .addComponent(jButtonSalir))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
        if(l!=null){
            try {
                double total = 0;
                Inventario i = sisLiquidaciones.devolverUltimoInventario(l.getFecha(), l.getReparto());
                jTextFieldInventario.setText(df.format(i.getTotal()).replace(',', '.'));
                total = total + i.getTotal();
                if(SistemaMantenimiento.getInstance().devolverConfiguracionLiquidacion().isMostrarFiadoClientesCobraChofer()){
                    FiadoChofer fc = sisLiquidaciones.devolverUltimoFiadoChofer(l.getFecha(), l.getReparto());
                    jTextFieldFiadoChofer.setText(df.format(fc.getTotal()).replace(',', '.'));
                    total = total + fc.getTotal();
                }
                jLabelTotal.setText(df.format(total).replace(',', '.'));
            } catch (ParseException ex) {
                
            } catch (Exception ex) {
                String stakTrace = util.Util.obtenerStackTraceEnString(ex);
                SistemaUsuarios.getInstance().registrarExcepcion(ex.toString(), stakTrace);
                JOptionPane.showMessageDialog(this, Constantes.MensajeDeErrorGenerico, "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_formWindowActivated

    private void jButtonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalirActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButtonSalirActionPerformed

    private void jButtonVerInventarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVerInventarioActionPerformed
        // TODO add your handling code here:
        if(l == null){
            JOptionPane.showMessageDialog(this, "Para ver inventario primero debe estar en una liquidación", "Información", JOptionPane.INFORMATION_MESSAGE);
        } else {
            try {
                // TODO add your handling code here:
                IngresoInventario vii = new IngresoInventario(this, true);
                Inventario i = sisLiquidaciones.devolverUltimoInventario(l.getFecha(), l.getReparto());
                vii.setInventario(i);
                vii.setVisible(true);
            } catch (ParseException ex) {
                JOptionPane.showMessageDialog(this, "Error al cargar el inventario." + "\n" + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            } catch (Exception ex) {
                String stakTrace = util.Util.obtenerStackTraceEnString(ex);
                SistemaUsuarios.getInstance().registrarExcepcion(ex.toString(), stakTrace);
                JOptionPane.showMessageDialog(this, Constantes.MensajeDeErrorGenerico, "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_jButtonVerInventarioActionPerformed

    private void jButtonVerFiadoChoferActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVerFiadoChoferActionPerformed
        // TODO add your handling code here:
        if(l == null){
            JOptionPane.showMessageDialog(this, "Para ver inventario primero debe estar en una liquidación", "Información", JOptionPane.INFORMATION_MESSAGE);
        } else {
            try {
                // TODO add your handling code here:
                IngresoFiadoChofer vfc = new IngresoFiadoChofer(this, true);
                FiadoChofer fc = sisLiquidaciones.devolverUltimoFiadoChofer(l.getFecha(), l.getReparto());
                vfc.setFiadoChofer(fc);
                vfc.setVisible(true);
            } catch (ParseException ex) {
                JOptionPane.showMessageDialog(this, "Error al cargar el inventario." + "\n" + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            } catch (Exception ex) {
                String stakTrace = util.Util.obtenerStackTraceEnString(ex);
                SistemaUsuarios.getInstance().registrarExcepcion(ex.toString(), stakTrace);
                JOptionPane.showMessageDialog(this, Constantes.MensajeDeErrorGenerico, "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_jButtonVerFiadoChoferActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaVerSaldoAnteriorLiquidacionNoAcumulativa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaVerSaldoAnteriorLiquidacionNoAcumulativa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaVerSaldoAnteriorLiquidacionNoAcumulativa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaVerSaldoAnteriorLiquidacionNoAcumulativa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                VentanaVerSaldoAnteriorLiquidacionNoAcumulativa dialog = new VentanaVerSaldoAnteriorLiquidacionNoAcumulativa(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    
    /**
     * @param l the l to set
     */
    public void setL(Liquidacion l) {
        this.l = l;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonSalir;
    private javax.swing.JButton jButtonVerFiadoChofer;
    private javax.swing.JButton jButtonVerInventario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelFiadoChofer;
    private javax.swing.JLabel jLabelTotal;
    private javax.swing.JTextField jTextFieldFiadoChofer;
    private javax.swing.JTextField jTextFieldInventario;
    // End of variables declaration//GEN-END:variables
}
