/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.mantenimiento;

import dominio.Articulo;
import dominio.GrupoDeArticulos;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import org.hibernate.HibernateException;
import sistema.SistemaMantenimientoArticulos;
import sistema.SistemaUsuarios;
import ui.usuarios.Constantes;

/**
 *
 * @author Edu
 */
public class MantenimientoGruposDeArticulos extends javax.swing.JDialog {

    private final SistemaMantenimientoArticulos sis;
    private GrupoDeArticulos grupoDeArticulos;
    private List<GrupoDeArticulos> gruposDeArticulos;

    private Articulo a;
    private List<Articulo> articulos;

    /**
     * Creates new form MantenimientoCamiones
     */
    public MantenimientoGruposDeArticulos(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        sis = SistemaMantenimientoArticulos.getInstance();
        articulos = new ArrayList<>();
        grupoDeArticulos = new GrupoDeArticulos();
        actualizarListaGruposDeArticulos();
        jButtonQuitar.setVisible(false);
        jTextFieldNombreGrupoDeArticulos.requestFocus();
        jTextFieldNombreGrupoDeArticulos.selectAll();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonSalir = new javax.swing.JButton();
        jButtonGuardar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListGruposDeArticulos = new javax.swing.JList();
        jButtonEliminar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldNombreGrupoDeArticulos = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldCodigoArticulo = new javax.swing.JTextField();
        jButtonAgregar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextAreaCodigos = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        jLabelDescripcion = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jButtonQuitar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jComboBoxFacturarDeA = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Mantenimiento Camiones");

        jButtonSalir.setText("Salir");
        jButtonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalirActionPerformed(evt);
            }
        });

        jButtonGuardar.setText("Guardar");
        jButtonGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGuardarActionPerformed(evt);
            }
        });
        jButtonGuardar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButtonGuardarKeyPressed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel1.setText("Grupos de Artículos");

        jListGruposDeArticulos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jListGruposDeArticulosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jListGruposDeArticulos);

        jButtonEliminar.setText("Eliminar");
        jButtonEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEliminarActionPerformed(evt);
            }
        });

        jLabel4.setText("Nombre: ");

        jTextFieldNombreGrupoDeArticulos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldNombreGrupoDeArticulosKeyPressed(evt);
            }
        });

        jLabel2.setText("Codigo:");

        jTextFieldCodigoArticulo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldCodigoArticuloKeyPressed(evt);
            }
        });

        jButtonAgregar.setText("Agregar");
        jButtonAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAgregarActionPerformed(evt);
            }
        });
        jButtonAgregar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButtonAgregarKeyPressed(evt);
            }
        });

        jTextAreaCodigos.setEditable(false);
        jTextAreaCodigos.setColumns(20);
        jTextAreaCodigos.setRows(5);
        jScrollPane2.setViewportView(jTextAreaCodigos);

        jLabel3.setText("Descripción:");

        jLabelDescripcion.setText("Descripción");

        jLabel12.setForeground(new java.awt.Color(255, 0, 0));
        jLabel12.setToolTipText("");

        jButtonQuitar.setText("Quitar");
        jButtonQuitar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonQuitarActionPerformed(evt);
            }
        });
        jButtonQuitar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButtonQuitarKeyPressed(evt);
            }
        });

        jLabel5.setText("Facturar de a:");

        jComboBoxFacturarDeA.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "10", "15", "20", "25", "30", "35", "40", " " }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldNombreGrupoDeArticulos, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTextFieldCodigoArticulo, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButtonAgregar))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelDescripcion)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel12))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jButtonGuardar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButtonSalir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButtonEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(77, 77, 77))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel5)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jComboBoxFacturarDeA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonQuitar)
                .addContainerGap(50, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jTextFieldNombreGrupoDeArticulos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jTextFieldCodigoArticulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonAgregar)
                            .addComponent(jButtonQuitar))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jLabelDescripcion)
                            .addComponent(jLabel12))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jComboBoxFacturarDeA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonGuardar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonEliminar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonSalir))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 53, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalirActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_jButtonSalirActionPerformed

    private void jListGruposDeArticulosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jListGruposDeArticulosMouseClicked
        // TODO add your handling code here:
        int seleccionado = jListGruposDeArticulos.getSelectedIndex();
        if (seleccionado != -1) {
            articulos = new ArrayList<>();
            grupoDeArticulos = gruposDeArticulos.get(seleccionado);
            jTextFieldNombreGrupoDeArticulos.setText(grupoDeArticulos.getNombre());
            articulos = grupoDeArticulos.getArticulos();
            jComboBoxFacturarDeA.setSelectedIndex(devolverIndiceComboFacturarDeA());
            jTextAreaCodigos.setText(armarStringCodigosArticulos(articulos));
        }
    }//GEN-LAST:event_jListGruposDeArticulosMouseClicked

    private void jButtonEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEliminarActionPerformed
        // TODO add your handling code here:
        if (grupoDeArticulos.getNombre() == null) {
            JOptionPane.showMessageDialog(this, "Para eliminar un grupo de articulos, primero debes seleccionarlo de la lista.", "Información", JOptionPane.INFORMATION_MESSAGE);
        } else {
            try {
                sis.eliminarGrupoDeArticulos(grupoDeArticulos);
                vaciarCampos();
                grupoDeArticulos = new GrupoDeArticulos();
                actualizarListaGruposDeArticulos();
            } catch (HibernateException e) {
                JOptionPane.showMessageDialog(this, "Error al eliminar el grupo de articulos." + "\n\n" + e.toString(), "Error", JOptionPane.ERROR_MESSAGE);
            } catch (Exception ex) {
                String stakTrace = util.Util.obtenerStackTraceEnString(ex);
                SistemaUsuarios.getInstance().registrarExcepcion(ex.toString(), stakTrace);
                JOptionPane.showMessageDialog(this, "Error al eliminar el grupo de articulos." + "\n\n" + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_jButtonEliminarActionPerformed

    private void jButtonGuardarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButtonGuardarKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jButtonGuardar.doClick();
        }
    }//GEN-LAST:event_jButtonGuardarKeyPressed

    private void jTextFieldNombreGrupoDeArticulosKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldNombreGrupoDeArticulosKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jTextFieldCodigoArticulo.requestFocus();
            jTextFieldCodigoArticulo.selectAll();
        }
    }//GEN-LAST:event_jTextFieldNombreGrupoDeArticulosKeyPressed

    private void jButtonGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGuardarActionPerformed
        // TODO add your handling code here:
        if ("".equals(jTextFieldNombreGrupoDeArticulos.getText().trim())) {
            JOptionPane.showMessageDialog(this, "El grupo de articulos debe tener un nombre.", "Información", JOptionPane.INFORMATION_MESSAGE);
            jTextFieldNombreGrupoDeArticulos.requestFocus();
            jTextFieldNombreGrupoDeArticulos.selectAll();
        } else {
            try {
                //Verifico que no exista un grupo de cl con ese nombre
                if (grupoDeArticulos.getNombre() == null) {
                    //Aca se agrega un nuevo grupo de articulos
                    //Verifico que sea un nombre valido, que no este repetido
                    if (!codigoValido(jTextFieldNombreGrupoDeArticulos.getText())) {
                        JOptionPane.showMessageDialog(this, "Ya existe un grupo de articulos con ese nombre.", "Información", JOptionPane.INFORMATION_MESSAGE);
                        jTextFieldNombreGrupoDeArticulos.requestFocus();
                        jTextFieldNombreGrupoDeArticulos.selectAll();
                    } else if (sis.agregarGrupoDeArticulos(jTextFieldNombreGrupoDeArticulos.getText().trim(), articulos, Integer.parseInt((String)jComboBoxFacturarDeA.getSelectedItem()))) {
                        jTextFieldNombreGrupoDeArticulos.setText("");
                        jTextAreaCodigos.setText("");
                        jTextFieldCodigoArticulo.setText("");
                        jLabelDescripcion.setText("");
                        jComboBoxFacturarDeA.setSelectedIndex(0);
                        grupoDeArticulos = new GrupoDeArticulos();
                        articulos = new ArrayList<>();
                        actualizarListaGruposDeArticulos();
                        jTextFieldNombreGrupoDeArticulos.requestFocus();
                        jTextFieldNombreGrupoDeArticulos.selectAll();
                    } else {
                        JOptionPane.showMessageDialog(this, "Error al guardar el grupo de articulos.", "Error", JOptionPane.ERROR_MESSAGE);
                    }
                } else //Aca se actualiza un grupo de clientes existente
                //Chequeo se quiere cambiar el nombre
                if (!grupoDeArticulos.getNombre().equals(jTextFieldNombreGrupoDeArticulos.getText())) {
                    //Si quiere cambiar el nombre, verifico que sea un nombre valido
                    if (!codigoValido(jTextFieldNombreGrupoDeArticulos.getText())) {
                        JOptionPane.showMessageDialog(this, "Ya existe un grupo de articulos con ese nombre.", "Información", JOptionPane.INFORMATION_MESSAGE);
                        jTextFieldNombreGrupoDeArticulos.requestFocus();
                        jTextFieldNombreGrupoDeArticulos.selectAll();
                    } else {
                        //Si el nombre es valido actualizo los datos
                        grupoDeArticulos.setNombre(jTextFieldNombreGrupoDeArticulos.getText());
                        grupoDeArticulos.setArticulos(articulos);
                        grupoDeArticulos.setFacturarDeA(Integer.parseInt((String)jComboBoxFacturarDeA.getSelectedItem()));
                        sis.actualizarGrupoDeArticulos(grupoDeArticulos);
                        jTextFieldNombreGrupoDeArticulos.setText("");
                        jTextAreaCodigos.setText("");
                        jTextFieldCodigoArticulo.setText("");
                        jLabelDescripcion.setText("");
                        jComboBoxFacturarDeA.setSelectedIndex(0);
                        grupoDeArticulos = new GrupoDeArticulos();
                        articulos = new ArrayList<>();
                        actualizarListaGruposDeArticulos();
                        jTextFieldNombreGrupoDeArticulos.requestFocus();
                        jTextFieldNombreGrupoDeArticulos.selectAll();
                    }
                } else {
                    //Si no quiere cambiar el nombre todo bien, se guarda con el mismo nombre
                    grupoDeArticulos.setNombre(jTextFieldNombreGrupoDeArticulos.getText());
                    grupoDeArticulos.setArticulos(articulos);
                    grupoDeArticulos.setFacturarDeA(Integer.parseInt((String)jComboBoxFacturarDeA.getSelectedItem()));
                    sis.actualizarGrupoDeArticulos(grupoDeArticulos);
                    jTextFieldNombreGrupoDeArticulos.setText("");
                    jTextAreaCodigos.setText("");
                    jTextFieldCodigoArticulo.setText("");
                    jLabelDescripcion.setText("");
                    jComboBoxFacturarDeA.setSelectedIndex(0);
                    grupoDeArticulos = new GrupoDeArticulos();
                    articulos = new ArrayList<>();
                    actualizarListaGruposDeArticulos();
                    jTextFieldNombreGrupoDeArticulos.requestFocus();
                    jTextFieldNombreGrupoDeArticulos.selectAll();
                }
            } catch (Exception e) {
                String stakTrace = util.Util.obtenerStackTraceEnString(e);
                SistemaUsuarios.getInstance().registrarExcepcion(e.toString(), stakTrace);
                JOptionPane.showMessageDialog(this, Constantes.MensajeDeErrorGenerico, "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_jButtonGuardarActionPerformed

    private void jTextFieldCodigoArticuloKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldCodigoArticuloKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            //jTextFieldCantidadRenglon.requestFocus();
            //jTextFieldCantidadRenglon.selectAll();
            if ("".equals(jTextFieldCodigoArticulo.getText().trim())) {
                jLabel12.setText("El codigo de producto no es valido.");
                jLabelDescripcion.setText("");
                jTextFieldCodigoArticulo.requestFocus();
                jTextFieldCodigoArticulo.selectAll();
            } else {
                try {
                    int codigo = Integer.parseInt(jTextFieldCodigoArticulo.getText());
                    a = sis.devolverArticuloPorCodigo(codigo);
                    if (a != null) {
                        jLabelDescripcion.setText(a.getDescripcion());
                        jLabel12.setText("");
                        if (articulos.contains(a)) {
                            jButtonQuitar.setVisible(true);
                            jButtonQuitar.requestFocus();
                        } else {
                            jButtonAgregar.requestFocus();
                        }
                    } else {
                        jLabel12.setText("El codigo de producto no es valido.");
                        jLabelDescripcion.setText("");
                        jTextFieldCodigoArticulo.requestFocus();
                        jTextFieldCodigoArticulo.selectAll();
                    }
                } catch (NumberFormatException e) {
                    e.printStackTrace();
                    JOptionPane.showMessageDialog(this, "El codigo debe ser un numero entero.", "Información", JOptionPane.INFORMATION_MESSAGE);
                    jTextFieldCodigoArticulo.requestFocus();
                    jTextFieldCodigoArticulo.selectAll();
                } catch (Exception e) {
                    String stakTrace = util.Util.obtenerStackTraceEnString(e);
                    SistemaUsuarios.getInstance().registrarExcepcion(e.toString(), stakTrace);
                    JOptionPane.showMessageDialog(this, Constantes.MensajeDeErrorGenerico, "Error", JOptionPane.ERROR_MESSAGE);
                }
            }
        }
    }//GEN-LAST:event_jTextFieldCodigoArticuloKeyPressed

    private void jButtonAgregarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButtonAgregarKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jButtonAgregar.doClick();
        }
    }//GEN-LAST:event_jButtonAgregarKeyPressed

    private void jButtonAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAgregarActionPerformed
        // TODO add your handling code here:
        articulos.add(a);
        if (jTextAreaCodigos.getText().equals("")) {
            jTextAreaCodigos.setText(Integer.toString(a.getCodigo()));
        } else {
            if (articulos.size() == 5 || articulos.size() == 10 || articulos.size() == 15 || articulos.size() == 20) {
                jTextAreaCodigos.setText(jTextAreaCodigos.getText() + "\n");
            }
            jTextAreaCodigos.setText(jTextAreaCodigos.getText() + ", " + a.getCodigo());
        }
        jTextFieldCodigoArticulo.setText("");
        jTextFieldCodigoArticulo.requestFocus();
        jTextFieldCodigoArticulo.selectAll();
    }//GEN-LAST:event_jButtonAgregarActionPerformed

    private void jButtonQuitarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonQuitarActionPerformed
        // TODO add your handling code here:
        articulos.remove(a);
        jTextAreaCodigos.setText(armarStringCodigosArticulos(articulos));
        jButtonQuitar.setVisible(false);
        jTextFieldCodigoArticulo.setText("");
        jTextFieldCodigoArticulo.requestFocus();
        jTextFieldCodigoArticulo.selectAll();
    }//GEN-LAST:event_jButtonQuitarActionPerformed

    private void jButtonQuitarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButtonQuitarKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jButtonQuitar.doClick();
        }
    }//GEN-LAST:event_jButtonQuitarKeyPressed

    private void actualizarListaGruposDeArticulos() {
        gruposDeArticulos = sis.devolverGruposDeArticulos();

        DefaultListModel modelo = new DefaultListModel();
        for (GrupoDeArticulos gda : gruposDeArticulos) {
            modelo.addElement(gda);
        }

        jListGruposDeArticulos.setModel(modelo);
    }

    private void vaciarCampos() {
        jTextFieldNombreGrupoDeArticulos.setText("");
        jTextAreaCodigos.setText("");
    }

    private boolean codigoValido(String cod) {
        boolean retorno = true;
        for (GrupoDeArticulos gda : gruposDeArticulos) {
            if (gda.getNombre().equals(cod)) {
                retorno = false;
                break;
            }
        }
        return retorno;
    }

    public String armarStringCodigosArticulos(List<Articulo> articulos) {
        String retorno = "";
        int cant = 0;
        for (Articulo art : articulos) {
            if (cant == 0) {
                retorno = retorno + art.getCodigo();
            } else {
                if (cant == 5 || cant == 10 || cant == 15 || cant == 20) {
                    retorno = retorno + "\n";
                }
                retorno = retorno + ", " + art.getCodigo();
            }
            cant++;
        }
        return retorno;
    }
    
    public int devolverIndiceComboFacturarDeA() {
        int retorno = 1;
        int cantidadDeOpciones = jComboBoxFacturarDeA.getItemCount();
        for(int i = 0; i<cantidadDeOpciones; i++) {
            if(Integer.toString(grupoDeArticulos.getFacturarDeA()).equals(jComboBoxFacturarDeA.getItemAt(i))) {
                retorno = i;
            }
        }
        return retorno;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MantenimientoGruposDeArticulos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MantenimientoGruposDeArticulos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MantenimientoGruposDeArticulos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MantenimientoGruposDeArticulos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                MantenimientoGruposDeArticulos dialog = new MantenimientoGruposDeArticulos(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAgregar;
    private javax.swing.JButton jButtonEliminar;
    private javax.swing.JButton jButtonGuardar;
    private javax.swing.JButton jButtonQuitar;
    private javax.swing.JButton jButtonSalir;
    private javax.swing.JComboBox<String> jComboBoxFacturarDeA;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabelDescripcion;
    private javax.swing.JList jListGruposDeArticulos;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextAreaCodigos;
    private javax.swing.JTextField jTextFieldCodigoArticulo;
    private javax.swing.JTextField jTextFieldNombreGrupoDeArticulos;
    // End of variables declaration//GEN-END:variables
}
