/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.clientes;

import dominio.Cliente;
import dominio.GrupoCliente;
import dominio.ProductoClienteProrrateo;
import dominio.Reparto;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import sistema.SistemaMantenimiento;

/**
 *
 * @author Edu
 */
public class IngresarCliente extends javax.swing.JFrame {

    private final SistemaMantenimiento sis;

    private String accion;

    private Cliente cliente;

    List<Reparto> repartos;
    List<GrupoCliente> grupoDeClientes;
    List<ProductoClienteProrrateo> productosClienteProrrateo;
    
    List<ProductoClienteProrrateo> prodsCliNuevo;

    /**
     * Creates new form IngresarCliente
     */
    public IngresarCliente(java.awt.Frame parent, boolean modal) {
        //super(parent, modal);
        initComponents();
        ocultraCamposProrrateo();
        sis = SistemaMantenimiento.getInstance();
        jComboBoxReparto.addItem("");
        repartos = sis.devolverRepartos();
        for (Reparto c : repartos) {
            jComboBoxReparto.addItem(c);
        }
        jComboBoxGruposDeClientes.addItem("");
        grupoDeClientes = sis.devolverGrupoCliente();
        for (GrupoCliente gc : grupoDeClientes) {
            jComboBoxGruposDeClientes.addItem(gc);
        }
        jComboBoxReparto.requestFocus();
    }

    public final void ocultraCamposProrrateo() {
        jLabelLitrosComun.setVisible(false);
        jLabelLitrosUltra.setVisible(false);
        jLabelLitrosDeslactosada.setVisible(false);
        jLabelProductos.setVisible(false);
        jTextFieldLitrosComun.setVisible(false);
        jTextFieldLitrosUltra.setVisible(false);
        jTextFieldLitrosDeslactosada.setVisible(false);
        jTextFieldProductos.setVisible(false);
        jComboBoxFrecFactLeche.setVisible(false);
        jComboBoxFrecFactProductos.setVisible(false);
        jButtonAgregarProducto.setVisible(false);
        jPanelProductos.setVisible(false);
        jLabelFrecFactProductos.setVisible(false);
        jLabelFrecFavtLeche.setVisible(false);
        jLabelProds.setVisible(false);
        jLabelFrecFavtLecheUltra.setVisible(false);
        jLabelFrecFavtLecheDeslca.setVisible(false);
        jComboBoxFrecFactLecheUltra.setVisible(false);
        jComboBoxFrecFactLecheDeslactosada.setVisible(false);
    }

    public final void mostrarCamposProrrateo() {
        jLabelLitrosComun.setVisible(true);
        jLabelLitrosUltra.setVisible(true);
        jLabelLitrosDeslactosada.setVisible(true);
        jLabelProductos.setVisible(true);
        jTextFieldLitrosComun.setVisible(true);
        jTextFieldLitrosUltra.setVisible(true);
        jTextFieldLitrosDeslactosada.setVisible(true);
        jTextFieldProductos.setVisible(true);
        jComboBoxFrecFactLeche.setVisible(true);
        jComboBoxFrecFactProductos.setVisible(true);
        jButtonAgregarProducto.setVisible(true);
        jPanelProductos.setVisible(true);
        jLabelFrecFactProductos.setVisible(true);
        jLabelFrecFavtLeche.setVisible(true);
        jLabelProds.setVisible(true);
        jLabelFrecFavtLecheUltra.setVisible(true);
        jLabelFrecFavtLecheDeslca.setVisible(true);
        jComboBoxFrecFactLecheUltra.setVisible(true);
        jComboBoxFrecFactLecheDeslactosada.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        jLabelTitulo = new javax.swing.JLabel();
        jRadioButtonManual = new javax.swing.JRadioButton();
        jRadioButtonProrrateo = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jRadioButtonActivo = new javax.swing.JRadioButton();
        jRadioButtonInActivo = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jButtonGuardar = new javax.swing.JButton();
        jButtonSalir = new javax.swing.JButton();
        jComboBoxReparto = new javax.swing.JComboBox();
        jTextFieldNombre = new javax.swing.JTextField();
        jTextFieldRut = new javax.swing.JTextField();
        jTextFieldDireccion = new javax.swing.JTextField();
        jTextFieldTelefono = new javax.swing.JTextField();
        jTextFieldEmail = new javax.swing.JTextField();
        jLabelLitrosComun = new javax.swing.JLabel();
        jLabelLitrosUltra = new javax.swing.JLabel();
        jLabelProductos = new javax.swing.JLabel();
        jTextFieldLitrosComun = new javax.swing.JTextField();
        jTextFieldLitrosUltra = new javax.swing.JTextField();
        jTextFieldProductos = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jRadioButtonChofer = new javax.swing.JRadioButton();
        jRadioButtonEmpresa = new javax.swing.JRadioButton();
        jComboBoxGruposDeClientes = new javax.swing.JComboBox();
        jLabelFrecFavtLeche = new javax.swing.JLabel();
        jLabelFrecFactProductos = new javax.swing.JLabel();
        jComboBoxFrecFactLeche = new javax.swing.JComboBox<>();
        jComboBoxFrecFactProductos = new javax.swing.JComboBox<>();
        jButtonAgregarProducto = new javax.swing.JButton();
        jLabelProds = new javax.swing.JLabel();
        jPanelProductos = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListProductos = new javax.swing.JList<>();
        jLabel11 = new javax.swing.JLabel();
        jTextFieldCodigoPS = new javax.swing.JTextField();
        jLabelLitrosDeslactosada = new javax.swing.JLabel();
        jTextFieldLitrosDeslactosada = new javax.swing.JTextField();
        jTextFieldRazonSocial = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabelFrecFavtLecheUltra = new javax.swing.JLabel();
        jComboBoxFrecFactLecheUltra = new javax.swing.JComboBox<>();
        jComboBoxFrecFactLecheDeslactosada = new javax.swing.JComboBox<>();
        jLabelFrecFavtLecheDeslca = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jTextFieldSucursalPS = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Datos Cliente");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jLabelTitulo.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabelTitulo.setForeground(new java.awt.Color(0, 0, 255));
        jLabelTitulo.setText("Cliente");

        buttonGroup1.add(jRadioButtonManual);
        jRadioButtonManual.setText("Manual");

        buttonGroup1.add(jRadioButtonProrrateo);
        jRadioButtonProrrateo.setText("Prorrateo");
        jRadioButtonProrrateo.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jRadioButtonProrrateoStateChanged(evt);
            }
        });

        jLabel1.setText("Tipo:");

        jLabel2.setText("Estado: ");

        buttonGroup2.add(jRadioButtonActivo);
        jRadioButtonActivo.setText("Activo");

        buttonGroup2.add(jRadioButtonInActivo);
        jRadioButtonInActivo.setText("InActivo");

        jLabel3.setText("Reparto:");

        jLabel4.setText("Nombre:");

        jLabel5.setText("RUT:");

        jLabel6.setText("Dirección:");

        jLabel7.setText("Teléfono:");

        jLabel8.setText("E-mail:");

        jButtonGuardar.setText("Guardar (F10)");
        jButtonGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGuardarActionPerformed(evt);
            }
        });
        jButtonGuardar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButtonGuardarKeyPressed(evt);
            }
        });

        jButtonSalir.setText("Salir");
        jButtonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalirActionPerformed(evt);
            }
        });
        jButtonSalir.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButtonSalirKeyPressed(evt);
            }
        });

        jComboBoxReparto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jComboBoxRepartoKeyPressed(evt);
            }
        });

        jTextFieldNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldNombreKeyPressed(evt);
            }
        });

        jTextFieldRut.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldRutKeyPressed(evt);
            }
        });

        jTextFieldDireccion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldDireccionKeyPressed(evt);
            }
        });

        jTextFieldTelefono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldTelefonoKeyPressed(evt);
            }
        });

        jTextFieldEmail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldEmailKeyPressed(evt);
            }
        });

        jLabelLitrosComun.setText("Litros Común:");

        jLabelLitrosUltra.setText("Litros Ultra:");

        jLabelProductos.setText("Productos:");

        jTextFieldLitrosComun.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldLitrosComunKeyPressed(evt);
            }
        });

        jTextFieldLitrosUltra.setText("0");
        jTextFieldLitrosUltra.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldLitrosUltraKeyPressed(evt);
            }
        });

        jTextFieldProductos.setText("0");
        jTextFieldProductos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldProductosKeyPressed(evt);
            }
        });

        jLabel9.setText("Cobra:");

        jLabel10.setText("Grupo de Cliente:");

        buttonGroup3.add(jRadioButtonChofer);
        jRadioButtonChofer.setText("Chofer");

        buttonGroup3.add(jRadioButtonEmpresa);
        jRadioButtonEmpresa.setText("Empresa");

        jLabelFrecFavtLeche.setText("Frecuencia Facturación:");

        jLabelFrecFactProductos.setText("Frecuencia Facturación:");

        jComboBoxFrecFactLeche.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1 Vez por Semana", "2 Veces por Semana", "3 Veces por Semana", "4 Veces por Semana", "5 Veces por Semana", "6 Veces por Semana", "7 Veces por Semana", "Cada 15 Dias", "1 vez por Mes" }));
        jComboBoxFrecFactLeche.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jComboBoxFrecFactLecheKeyPressed(evt);
            }
        });

        jComboBoxFrecFactProductos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1 Vez por Semana", "2 Veces por Semana", "3 Veces por Semana", "4 Veces por Semana", "5 Veces por Semana", "6 Veces por Semana", "7 Veces por Semana", "Cada 15 Dias", "1 vez por Mes" }));
        jComboBoxFrecFactProductos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jComboBoxFrecFactProductosKeyPressed(evt);
            }
        });

        jButtonAgregarProducto.setText("Agregar Producto");
        jButtonAgregarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAgregarProductoActionPerformed(evt);
            }
        });
        jButtonAgregarProducto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButtonAgregarProductoKeyPressed(evt);
            }
        });

        jLabelProds.setText("Productos:");

        jListProductos.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jListProductos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jListProductosKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(jListProductos);

        javax.swing.GroupLayout jPanelProductosLayout = new javax.swing.GroupLayout(jPanelProductos);
        jPanelProductos.setLayout(jPanelProductosLayout);
        jPanelProductosLayout.setHorizontalGroup(
            jPanelProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        jPanelProductosLayout.setVerticalGroup(
            jPanelProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelProductosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(87, Short.MAX_VALUE))
        );

        jLabel11.setText("Codigo Cliente en PS:");

        jTextFieldCodigoPS.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldCodigoPSKeyPressed(evt);
            }
        });

        jLabelLitrosDeslactosada.setText("L Deslactosada:");

        jTextFieldLitrosDeslactosada.setText("0");
        jTextFieldLitrosDeslactosada.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldLitrosDeslactosadaKeyPressed(evt);
            }
        });

        jTextFieldRazonSocial.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldRazonSocialKeyPressed(evt);
            }
        });

        jLabel12.setText("Razon Social:");

        jLabelFrecFavtLecheUltra.setText("Frecuencia Facturación:");

        jComboBoxFrecFactLecheUltra.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1 Vez por Semana", "2 Veces por Semana", "3 Veces por Semana", "4 Veces por Semana", "5 Veces por Semana", "6 Veces por Semana", "7 Veces por Semana", "Cada 15 Dias", "1 vez por Mes" }));
        jComboBoxFrecFactLecheUltra.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jComboBoxFrecFactLecheUltraKeyPressed(evt);
            }
        });

        jComboBoxFrecFactLecheDeslactosada.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1 Vez por Semana", "2 Veces por Semana", "3 Veces por Semana", "4 Veces por Semana", "5 Veces por Semana", "6 Veces por Semana", "7 Veces por Semana", "Cada 15 Dias", "1 vez por Mes" }));
        jComboBoxFrecFactLecheDeslactosada.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jComboBoxFrecFactLecheDeslactosadaKeyPressed(evt);
            }
        });

        jLabelFrecFavtLecheDeslca.setText("Frecuencia Facturación:");

        jLabel13.setText("SucursalPS:");

        jTextFieldSucursalPS.setText("1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(427, 427, 427)
                        .addComponent(jLabelTitulo))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(397, 397, 397)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jButtonGuardar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(37, 37, 37)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel3)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jComboBoxReparto, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel4)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jTextFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel10)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jComboBoxGruposDeClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(132, 132, 132))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel5)
                                            .addComponent(jLabel6)
                                            .addComponent(jLabel7)
                                            .addComponent(jLabel8)
                                            .addComponent(jLabel12))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jTextFieldDireccion, javax.swing.GroupLayout.DEFAULT_SIZE, 330, Short.MAX_VALUE)
                                            .addComponent(jTextFieldTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTextFieldEmail, javax.swing.GroupLayout.DEFAULT_SIZE, 330, Short.MAX_VALUE)
                                            .addComponent(jTextFieldRut, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTextFieldRazonSocial))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelProductos, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabelLitrosDeslactosada, javax.swing.GroupLayout.Alignment.TRAILING)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(107, 107, 107)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel9))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jRadioButtonChofer)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jRadioButtonEmpresa))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jRadioButtonManual)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jRadioButtonProrrateo)))
                                        .addGap(173, 173, 173)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabelLitrosUltra, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabelLitrosComun)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel11)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextFieldCodigoPS, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel13)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextFieldSucursalPS, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jRadioButtonActivo)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jRadioButtonInActivo))
                                        .addComponent(jTextFieldLitrosComun)
                                        .addComponent(jTextFieldProductos)
                                        .addComponent(jTextFieldLitrosUltra))
                                    .addComponent(jButtonAgregarProducto, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addComponent(jLabelProds))
                            .addComponent(jTextFieldLitrosDeslactosada))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelProductos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelFrecFavtLeche)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBoxFrecFactLeche, 0, 1, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelFrecFavtLecheUltra)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBoxFrecFactLecheUltra, 0, 1, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelFrecFactProductos)
                            .addComponent(jLabelFrecFavtLecheDeslca))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBoxFrecFactLecheDeslactosada, javax.swing.GroupLayout.Alignment.TRAILING, 0, 1, Short.MAX_VALUE)
                            .addComponent(jComboBoxFrecFactProductos, 0, 172, Short.MAX_VALUE))))
                .addGap(12, 12, 12))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabelTitulo)
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jTextFieldCodigoPS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(jTextFieldSucursalPS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jRadioButtonActivo)
                    .addComponent(jRadioButtonInActivo)
                    .addComponent(jRadioButtonManual)
                    .addComponent(jRadioButtonProrrateo)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jRadioButtonChofer)
                    .addComponent(jRadioButtonEmpresa))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jComboBoxGruposDeClientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelLitrosComun)
                    .addComponent(jTextFieldLitrosComun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelFrecFavtLeche)
                    .addComponent(jComboBoxFrecFactLeche, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jComboBoxReparto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelLitrosUltra)
                    .addComponent(jTextFieldLitrosUltra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelFrecFavtLecheUltra)
                    .addComponent(jComboBoxFrecFactLecheUltra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelLitrosDeslactosada)
                    .addComponent(jTextFieldLitrosDeslactosada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxFrecFactLecheDeslactosada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelFrecFavtLecheDeslca))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldRazonSocial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(jLabelProductos)
                    .addComponent(jTextFieldProductos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelFrecFactProductos)
                    .addComponent(jComboBoxFrecFactProductos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelProductos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButtonGuardar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonSalir))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelProds)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel5)
                                .addComponent(jTextFieldRut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)
                            .addComponent(jButtonAgregarProducto))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jTextFieldTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(jTextFieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 93, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalirActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButtonSalirActionPerformed

    private void jRadioButtonProrrateoStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jRadioButtonProrrateoStateChanged
        // TODO add your handling code here:
        if (jRadioButtonProrrateo.isSelected()) {
            mostrarCamposProrrateo();
        } else {
            ocultraCamposProrrateo();
        }
    }//GEN-LAST:event_jRadioButtonProrrateoStateChanged

    private void jButtonGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGuardarActionPerformed
        // TODO add your handling code here:
        if (getCliente() == null) {
            //Es un cliente nuevo
            if (jRadioButtonProrrateo.isSelected()) {
                //Es un cliente prorrateo
                if ("".equals(jTextFieldLitrosComun.getText().trim()) || "".equals(jTextFieldLitrosUltra.getText().trim()) || "".equals(jTextFieldProductos.getText().trim())) {
                    JOptionPane.showMessageDialog(this, "Si el tipo de Cliente es prorrateo, debe ingresar los litros de leche comun y ultra que compra y los productos. Si no compra algunos ingresamos cero.", "Información", JOptionPane.INFORMATION_MESSAGE);
                    jTextFieldLitrosComun.requestFocus();
                    jTextFieldLitrosComun.selectAll();
                } else if (jComboBoxReparto.getSelectedIndex() == 0) {
                    JOptionPane.showMessageDialog(this, "Debe seleccionar un reparto.", "Información", JOptionPane.INFORMATION_MESSAGE);
                    jComboBoxReparto.requestFocus();
                } else if ("".equals(jTextFieldNombre.getText().trim())) {
                    JOptionPane.showMessageDialog(this, "Debe ingresar un nombre para el cliente.", "Información", JOptionPane.INFORMATION_MESSAGE);
                    jTextFieldNombre.requestFocus();
                } else {
                    //Datos correctos Guardo el Cliente
                    boolean prorrateo = jRadioButtonProrrateo.isSelected();
                    boolean activo = jRadioButtonActivo.isSelected();
                    boolean cobraChofer = jRadioButtonChofer.isSelected();
                    GrupoCliente gc = null;
                    if (jComboBoxGruposDeClientes.getSelectedIndex() != 0) {
                        gc = (GrupoCliente) jComboBoxGruposDeClientes.getSelectedItem();
                    }
                    Reparto r = (Reparto) jComboBoxReparto.getSelectedItem();
                    String nombre = jTextFieldNombre.getText().trim();
                    String razonSocial = jTextFieldRazonSocial.getText().trim();
                    String rut = jTextFieldRut.getText().trim();
                    String direccion = jTextFieldDireccion.getText().trim();
                    String telefono = jTextFieldTelefono.getText().trim();
                    String email = jTextFieldEmail.getText().trim();
                    try {
                        int lComun = Integer.parseInt(jTextFieldLitrosComun.getText().trim());
                        int lUltra = Integer.parseInt(jTextFieldLitrosUltra.getText().trim());
                        int lDeslactosada = Integer.parseInt(jTextFieldLitrosDeslactosada.getText().trim());
                        long codigoPS;
                        if("".equals(jTextFieldCodigoPS.getText().trim())){
                            codigoPS = 0;
                        } else {
                            codigoPS = Long.parseLong(jTextFieldCodigoPS.getText().trim());
                        }
                        int sucursalPS;
                        if("".equals(jTextFieldSucursalPS.getText().trim())){
                            sucursalPS = 1;
                        } else {
                            sucursalPS = Integer.parseInt(jTextFieldCodigoPS.getText().trim());
                        }
                        double prods = Double.parseDouble(jTextFieldProductos.getText().trim());
                        
                        if (sis.agregarCliente(prorrateo, activo, cobraChofer, gc, r, nombre, razonSocial, rut, direccion, telefono, email, lComun, lUltra, lDeslactosada, (String) jComboBoxFrecFactLeche.getSelectedItem(), prods, (String) jComboBoxFrecFactProductos.getSelectedItem(),codigoPS, sucursalPS, prodsCliNuevo, (String)jComboBoxFrecFactLecheUltra.getSelectedItem(), (String)jComboBoxFrecFactLecheDeslactosada.getSelectedItem())) {
                            JOptionPane.showMessageDialog(this, "Cliente guardado correctamente.", "Información", JOptionPane.INFORMATION_MESSAGE);
                            vaciarCampos();
                            jComboBoxReparto.requestFocus();
                        }
                    } catch (NumberFormatException e) {
                        e.printStackTrace();
                        JOptionPane.showMessageDialog(this, "Los litros de comun, ultra y productos deben ser numeros. Tambien el codigo PS", "Información", JOptionPane.INFORMATION_MESSAGE);
                    } catch (Exception e) {
                        JOptionPane.showMessageDialog(this, "Error al guardar el cliente. " + "\n" + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
                    }

                }
            } else //Es un cliente manual
            if (jComboBoxReparto.getSelectedIndex() == 0) {
                JOptionPane.showMessageDialog(this, "Debe seleccionar un reparto.", "Información", JOptionPane.INFORMATION_MESSAGE);
                jComboBoxReparto.requestFocus();
            } else if ("".equals(jTextFieldNombre.getText().trim())) {
                JOptionPane.showMessageDialog(this, "Debe ingresar un nombre para el cliente.", "Información", JOptionPane.INFORMATION_MESSAGE);
                jTextFieldNombre.requestFocus();
            } else {
                //Datos correctos Guardo el Cliente
                boolean prorrateo = jRadioButtonProrrateo.isSelected();
                boolean activo = jRadioButtonActivo.isSelected();
                boolean cobraChofer = jRadioButtonChofer.isSelected();
                GrupoCliente gc = null;
                if (jComboBoxGruposDeClientes.getSelectedIndex() != 0) {
                    gc = (GrupoCliente) jComboBoxGruposDeClientes.getSelectedItem();
                }
                Reparto r = (Reparto) jComboBoxReparto.getSelectedItem();
                String nombre = jTextFieldNombre.getText().trim();
                String razonSocial = jTextFieldRazonSocial.getText().trim();
                String rut = jTextFieldRut.getText().trim();
                String direccion = jTextFieldDireccion.getText().trim();
                String telefono = jTextFieldTelefono.getText().trim();
                String email = jTextFieldEmail.getText().trim();
                long codigoPS;
                if ("".equals(jTextFieldCodigoPS.getText().trim())) {
                    codigoPS = 0;
                } else {
                    codigoPS = Long.parseLong(jTextFieldCodigoPS.getText().trim());
                }
                int sucursalPS;
                        if("".equals(jTextFieldSucursalPS.getText().trim())){
                            sucursalPS = 1;
                        } else {
                            sucursalPS = Integer.parseInt(jTextFieldCodigoPS.getText().trim());
                        }
                try {
                    if (sis.agregarCliente(prorrateo, activo, cobraChofer, gc, r, nombre, razonSocial, rut, direccion, telefono, email, 0, 0, 0, "", 0, "",codigoPS, sucursalPS, prodsCliNuevo, "","")) {
                        JOptionPane.showMessageDialog(this, "Cliente guardado correctamente.", "Información", JOptionPane.INFORMATION_MESSAGE);
                        vaciarCampos();
                        jComboBoxReparto.requestFocus();
                    }
                } catch (NumberFormatException ne){
                    JOptionPane.showMessageDialog(this, "El codigo PS debe ser numerico.", "Información", JOptionPane.INFORMATION_MESSAGE);
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(this, "Error al guardar el cliente. " + "\n" + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
                }

            }
        } else //Es una modificacion.
        if (jRadioButtonProrrateo.isSelected()) {
            //Es un cliente prorrateo
            if ("".equals(jTextFieldLitrosComun.getText().trim()) || "".equals(jTextFieldLitrosUltra.getText().trim()) || "".equals(jTextFieldProductos.getText().trim())) {
                JOptionPane.showMessageDialog(this, "Si el tipo de Cliente es prorrateo, debe ingresar los litros de leche comun y ultra que compra y los productos. Si no compra algunos ingresamos cero.", "Información", JOptionPane.INFORMATION_MESSAGE);
                jTextFieldLitrosComun.requestFocus();
                jTextFieldLitrosComun.selectAll();
            } else if (jComboBoxReparto.getSelectedIndex() == 0) {
                JOptionPane.showMessageDialog(this, "Debe seleccionar un reparto.", "Información", JOptionPane.INFORMATION_MESSAGE);
                jComboBoxReparto.requestFocus();
            } else if ("".equals(jTextFieldNombre.getText().trim())) {
                JOptionPane.showMessageDialog(this, "Debe ingresar un nombre para el cliente.", "Información", JOptionPane.INFORMATION_MESSAGE);
                jTextFieldNombre.requestFocus();
            } else {
                //Datos correctos Guardo el Cliente
                cliente.setProrrateo(jRadioButtonProrrateo.isSelected());
                cliente.setActivo(jRadioButtonActivo.isSelected());
                cliente.setCobraChofer(jRadioButtonChofer.isSelected());
                GrupoCliente gc = null;
                if (jComboBoxGruposDeClientes.getSelectedIndex() != 0) {
                    cliente.setGrupoCliente((GrupoCliente) jComboBoxGruposDeClientes.getSelectedItem());
                }
                cliente.setReparto((Reparto) jComboBoxReparto.getSelectedItem());
                cliente.setNombre(jTextFieldNombre.getText().trim());
                cliente.setRazonSocial(jTextFieldRazonSocial.getText().trim());
                cliente.setRut(jTextFieldRut.getText().trim());
                cliente.setDireccion(jTextFieldDireccion.getText().trim());
                cliente.setTelefono(jTextFieldTelefono.getText().trim());
                cliente.setCorreoElectronico(jTextFieldEmail.getText().trim());
                cliente.setFrecuenciaFacturacionLeche((String) jComboBoxFrecFactLeche.getSelectedItem());
                cliente.setFrecuenciaFacturacionProductos((String) jComboBoxFrecFactProductos.getSelectedItem());
                try {
                    cliente.setLitrosComun(Integer.parseInt(jTextFieldLitrosComun.getText().trim()));
                    cliente.setLitrosUltra(Integer.parseInt(jTextFieldLitrosUltra.getText().trim()));
                    cliente.setLitrosDeslactosada(Integer.parseInt(jTextFieldLitrosDeslactosada.getText().trim()));
                    cliente.setProductos(Double.parseDouble(jTextFieldProductos.getText().trim()));
                    cliente.setCodigoPS(Long.parseLong(jTextFieldCodigoPS.getText().trim()));
                    cliente.setSucursalPS(Integer.parseInt(jTextFieldSucursalPS.getText().trim()));
                    if (sis.actualizarCliente(cliente)) {
                        JOptionPane.showMessageDialog(this, "Cliente guardado correctamente.", "Información", JOptionPane.INFORMATION_MESSAGE);
                        this.dispose();
                    }
                } catch (NumberFormatException e) {
                    e.printStackTrace();
                    JOptionPane.showMessageDialog(this, "Los litros de comun, ultra y productos deben ser numeros. Tambien el codigo PS.", "Información", JOptionPane.INFORMATION_MESSAGE);
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(this, "Error al guardar el cliente. " + "\n" + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
                }

            }
        } else //Es un cliente manual
        if (jComboBoxReparto.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(this, "Debe seleccionar un reparto.", "Información", JOptionPane.INFORMATION_MESSAGE);
            jComboBoxReparto.requestFocus();
        } else if ("".equals(jTextFieldNombre.getText().trim())) {
            JOptionPane.showMessageDialog(this, "Debe ingresar un nombre para el cliente.", "Información", JOptionPane.INFORMATION_MESSAGE);
            jTextFieldNombre.requestFocus();
        } else {
            //Datos correctos Guardo el Cliente
            cliente.setProrrateo(jRadioButtonProrrateo.isSelected());
            cliente.setActivo(jRadioButtonActivo.isSelected());
            cliente.setCobraChofer(jRadioButtonChofer.isSelected());
            GrupoCliente gc = null;
            if (jComboBoxGruposDeClientes.getSelectedIndex() != 0) {
                cliente.setGrupoCliente((GrupoCliente) jComboBoxGruposDeClientes.getSelectedItem());
            }
            cliente.setReparto((Reparto) jComboBoxReparto.getSelectedItem());
            cliente.setNombre(jTextFieldNombre.getText().trim());
            cliente.setRazonSocial(jTextFieldRazonSocial.getText().trim());
            cliente.setRut(jTextFieldRut.getText().trim());
            cliente.setDireccion(jTextFieldDireccion.getText().trim());
            cliente.setTelefono(jTextFieldTelefono.getText().trim());
            cliente.setCorreoElectronico(jTextFieldEmail.getText().trim());
            cliente.setCodigoPS(Long.parseLong(jTextFieldCodigoPS.getText().trim()));
            cliente.setSucursalPS(Integer.parseInt(jTextFieldSucursalPS.getText().trim()));
            try {
                if (sis.actualizarCliente(cliente)) {
                    JOptionPane.showMessageDialog(this, "Cliente guardado correctamente.", "Información", JOptionPane.INFORMATION_MESSAGE);
                    this.dispose();
                }
            } catch (NumberFormatException ne){
                JOptionPane.showMessageDialog(this, "El codigo PS debe ser un numero.", "Información", JOptionPane.INFORMATION_MESSAGE);
                jTextFieldCodigoPS.requestFocus();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Error al guardar el cliente. " + "\n" + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            }

        }
    }//GEN-LAST:event_jButtonGuardarActionPerformed

    public void vaciarCampos() {
        jComboBoxReparto.setSelectedIndex(0);
        jComboBoxGruposDeClientes.setSelectedIndex(0);
        jTextFieldNombre.setText("");
        jTextFieldRazonSocial.setText("");
        jTextFieldRut.setText("");
        jTextFieldDireccion.setText("");
        jTextFieldTelefono.setText("");
        jTextFieldEmail.setText("");
        jTextFieldLitrosComun.setText("");
        jTextFieldLitrosUltra.setText("0");
        jTextFieldLitrosDeslactosada.setText("0");
        jTextFieldProductos.setText("0");
        jRadioButtonActivo.setSelected(true);
        jRadioButtonManual.setSelected(true);
        jRadioButtonChofer.setSelected(true);
    }

    private void jComboBoxRepartoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jComboBoxRepartoKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jTextFieldNombre.requestFocus();
            jTextFieldNombre.selectAll();
        }
        if (evt.getKeyCode() == KeyEvent.VK_F10) {
            jButtonGuardar.doClick();
        }
    }//GEN-LAST:event_jComboBoxRepartoKeyPressed

    private void jTextFieldNombreKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldNombreKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jTextFieldRazonSocial.requestFocus();
            jTextFieldRazonSocial.selectAll();
        }
        if (evt.getKeyCode() == KeyEvent.VK_F10) {
            jButtonGuardar.doClick();
        }
    }//GEN-LAST:event_jTextFieldNombreKeyPressed

    private void jTextFieldRutKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldRutKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jTextFieldDireccion.requestFocus();
            jTextFieldDireccion.selectAll();
        }
        if (evt.getKeyCode() == KeyEvent.VK_F10) {
            jButtonGuardar.doClick();
        }
    }//GEN-LAST:event_jTextFieldRutKeyPressed

    private void jTextFieldDireccionKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldDireccionKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jTextFieldTelefono.requestFocus();
            jTextFieldTelefono.selectAll();
        }
        if (evt.getKeyCode() == KeyEvent.VK_F10) {
            jButtonGuardar.doClick();
        }
    }//GEN-LAST:event_jTextFieldDireccionKeyPressed

    private void jTextFieldTelefonoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldTelefonoKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jTextFieldEmail.requestFocus();
            jTextFieldEmail.selectAll();
        }
        if (evt.getKeyCode() == KeyEvent.VK_F10) {
            jButtonGuardar.doClick();
        }
    }//GEN-LAST:event_jTextFieldTelefonoKeyPressed

    private void jTextFieldEmailKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldEmailKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (jTextFieldLitrosComun.isVisible()) {
                jTextFieldLitrosComun.requestFocus();
                jTextFieldLitrosComun.selectAll();
            } else {
                jButtonGuardar.requestFocus();
            }
        }
        if (evt.getKeyCode() == KeyEvent.VK_F10) {
            jButtonGuardar.doClick();
        }
    }//GEN-LAST:event_jTextFieldEmailKeyPressed

    private void jButtonGuardarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButtonGuardarKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jButtonGuardar.doClick();
        }
    }//GEN-LAST:event_jButtonGuardarKeyPressed

    private void jTextFieldLitrosComunKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldLitrosComunKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jComboBoxFrecFactLeche.requestFocus();
        }
        if (evt.getKeyCode() == KeyEvent.VK_F10) {
            jButtonGuardar.doClick();
        }
    }//GEN-LAST:event_jTextFieldLitrosComunKeyPressed

    private void jTextFieldLitrosUltraKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldLitrosUltraKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jComboBoxFrecFactLecheUltra.requestFocus();
            //jTextFieldProductos.requestFocus();
            //jTextFieldProductos.selectAll();
        }
        if (evt.getKeyCode() == KeyEvent.VK_F10) {
            jButtonGuardar.doClick();
        }
    }//GEN-LAST:event_jTextFieldLitrosUltraKeyPressed

    private void jTextFieldProductosKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldProductosKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jComboBoxFrecFactProductos.requestFocus();
        }
        if (evt.getKeyCode() == KeyEvent.VK_F10) {
            jButtonGuardar.doClick();
        }
    }//GEN-LAST:event_jTextFieldProductosKeyPressed

    private void jButtonSalirKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButtonSalirKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jButtonSalir.doClick();
        }
    }//GEN-LAST:event_jButtonSalirKeyPressed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
        if ("Nuevo".equals(this.getAccion()) && cliente == null) {
            jRadioButtonActivo.setSelected(true);
            jRadioButtonChofer.setSelected(true);
            jRadioButtonManual.setSelected(true);
        }
        if ("Ver".equals(this.getAccion()) && getCliente() != null) {
            jRadioButtonActivo.setEnabled(false);
            jRadioButtonChofer.setEnabled(false);
            jRadioButtonEmpresa.setEnabled(false);
            jRadioButtonInActivo.setEnabled(false);
            jRadioButtonManual.setEnabled(false);
            jRadioButtonProrrateo.setEnabled(false);
            jComboBoxGruposDeClientes.setEnabled(false);
            jTextFieldCodigoPS.setEnabled(false);
            jTextFieldSucursalPS.setEnabled(false);
            jComboBoxReparto.setEnabled(false);
            jTextFieldDireccion.setEnabled(false);
            jTextFieldEmail.setEnabled(false);
            jTextFieldLitrosComun.setEnabled(false);
            jTextFieldLitrosUltra.setEnabled(false);
            jTextFieldLitrosDeslactosada.setEnabled(false);
            jTextFieldNombre.setEnabled(false);
            jTextFieldRazonSocial.setEnabled(false);
            jTextFieldProductos.setEnabled(false);
            jTextFieldRut.setEnabled(false);
            jTextFieldTelefono.setEnabled(false);
            jButtonGuardar.setEnabled(false);
            jComboBoxFrecFactLeche.setEnabled(false);
            jComboBoxFrecFactProductos.setEnabled(false);
            jButtonAgregarProducto.setEnabled(false);
            jListProductos.setEnabled(false);

            jRadioButtonProrrateo.setSelected(getCliente().isProrrateo());
            jRadioButtonActivo.setSelected(getCliente().isActivo());
            jRadioButtonChofer.setSelected(getCliente().isCobraChofer());
            jRadioButtonManual.setSelected(!getCliente().isProrrateo());
            jRadioButtonInActivo.setSelected(!getCliente().isActivo());
            jRadioButtonEmpresa.setSelected(!getCliente().isCobraChofer());
            jTextFieldCodigoPS.setText(Long.toString(getCliente().getCodigoPS()));
            jTextFieldSucursalPS.setText(Integer.toString(getCliente().getSucursalPS()));
            if (getCliente().getGrupoCliente() == null) {
                jComboBoxGruposDeClientes.setSelectedIndex(0);
            } else {
                int indiceGrupoCliente = this.devolverIndiceGrupoDeCliente(getCliente().getGrupoCliente());
                jComboBoxGruposDeClientes.setSelectedIndex(indiceGrupoCliente);
            }
            int indiceReparto = this.devolverIndiceReparto(getCliente().getReparto());
            jComboBoxReparto.setSelectedIndex(indiceReparto);
            jTextFieldNombre.setText(getCliente().getNombre());
            jTextFieldRazonSocial.setText(getCliente().getRazonSocial());
            jTextFieldRut.setText(getCliente().getRut());
            jTextFieldDireccion.setText(getCliente().getDireccion());
            jTextFieldTelefono.setText(getCliente().getTelefono());
            jTextFieldEmail.setText(getCliente().getCorreoElectronico());
            if (getCliente().isProrrateo()) {
                jTextFieldLitrosComun.setText(Integer.toString(getCliente().getLitrosComun()));
                jTextFieldLitrosUltra.setText(Integer.toString(getCliente().getLitrosUltra()));
                jTextFieldLitrosDeslactosada.setText(Integer.toString(getCliente().getLitrosDeslactosada()));
                jTextFieldProductos.setText(Double.toString(getCliente().getProductos()));
            }
            jComboBoxFrecFactLeche.setSelectedItem(getCliente().getFrecuenciaFacturacionLeche());
            jComboBoxFrecFactLecheUltra.setSelectedItem(getCliente().getFrecuenciaFacturacionLecheUltra());
            jComboBoxFrecFactLecheDeslactosada.setSelectedItem(getCliente().getFrecuenciaFacturacionLecheDeslactosada());
            jComboBoxFrecFactProductos.setSelectedItem(getCliente().getFrecuenciaFacturacionProductos());
            actualizarListaProductos();

        }
        if ("Modificar".equals(this.getAccion()) && getCliente() != null) {
            jRadioButtonProrrateo.setSelected(getCliente().isProrrateo());
            jRadioButtonActivo.setSelected(getCliente().isActivo());
            jRadioButtonChofer.setSelected(getCliente().isCobraChofer());
            jRadioButtonManual.setSelected(!getCliente().isProrrateo());
            jRadioButtonInActivo.setSelected(!getCliente().isActivo());
            jRadioButtonEmpresa.setSelected(!getCliente().isCobraChofer());
            jTextFieldCodigoPS.setText(Long.toString(getCliente().getCodigoPS()));
            jTextFieldSucursalPS.setText(Integer.toString(getCliente().getSucursalPS()));
            if (getCliente().getGrupoCliente() == null) {
                jComboBoxGruposDeClientes.setSelectedIndex(0);
            } else {
                int indiceGrupoCliente = this.devolverIndiceGrupoDeCliente(getCliente().getGrupoCliente());
                jComboBoxGruposDeClientes.setSelectedIndex(indiceGrupoCliente);
            }
            int indiceReparto = this.devolverIndiceReparto(getCliente().getReparto());
            jComboBoxReparto.setSelectedIndex(indiceReparto);
            //jComboBoxReparto.setSelectedItem(getCliente().getReparto());
            jTextFieldNombre.setText(getCliente().getNombre());
            jTextFieldRazonSocial.setText(getCliente().getRazonSocial());
            jTextFieldRut.setText(getCliente().getRut());
            jTextFieldDireccion.setText(getCliente().getDireccion());
            jTextFieldTelefono.setText(getCliente().getTelefono());
            jTextFieldEmail.setText(getCliente().getCorreoElectronico());
            if (getCliente().isProrrateo()) {
                jTextFieldLitrosComun.setText(Integer.toString(getCliente().getLitrosComun()));
                jTextFieldLitrosUltra.setText(Integer.toString(getCliente().getLitrosUltra()));
                jTextFieldLitrosDeslactosada.setText(Integer.toString(getCliente().getLitrosDeslactosada()));
                jTextFieldProductos.setText(Double.toString(getCliente().getProductos()));
            }
            jComboBoxFrecFactLeche.setSelectedItem(getCliente().getFrecuenciaFacturacionLeche());
            jComboBoxFrecFactLecheUltra.setSelectedItem(getCliente().getFrecuenciaFacturacionLecheUltra());
            jComboBoxFrecFactLecheDeslactosada.setSelectedItem(getCliente().getFrecuenciaFacturacionLecheDeslactosada());
            jComboBoxFrecFactProductos.setSelectedItem(getCliente().getFrecuenciaFacturacionProductos());
            actualizarListaProductos();
        }
        if ("AgregarProducto".equals(this.getAccion()) ) {
            actualizarListaProductos();
        }
    }//GEN-LAST:event_formWindowActivated

    private void jButtonAgregarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAgregarProductoActionPerformed
        // TODO add your handling code here:
        AgregarProductoClienteProrrateo vapcp = new AgregarProductoClienteProrrateo(IngresarCliente.this, true);
        vapcp.setCli(cliente);
        if(prodsCliNuevo == null) {
            prodsCliNuevo = new ArrayList<>();
        }
        vapcp.setProdsCliNuevo(prodsCliNuevo);
        vapcp.setVisible(true);
        this.setAccion("AgregarProducto");
        jButtonGuardar.requestFocus();
    }//GEN-LAST:event_jButtonAgregarProductoActionPerformed

    private void jComboBoxFrecFactLecheKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jComboBoxFrecFactLecheKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jTextFieldLitrosUltra.requestFocus();
            jTextFieldLitrosUltra.selectAll();
        }
        if (evt.getKeyCode() == KeyEvent.VK_F10) {
            jButtonGuardar.doClick();
        }
    }//GEN-LAST:event_jComboBoxFrecFactLecheKeyPressed

    private void jComboBoxFrecFactProductosKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jComboBoxFrecFactProductosKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jButtonAgregarProducto.requestFocus();
        }
        if (evt.getKeyCode() == KeyEvent.VK_F10) {
            jButtonGuardar.doClick();
        }
    }//GEN-LAST:event_jComboBoxFrecFactProductosKeyPressed

    private void jButtonAgregarProductoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButtonAgregarProductoKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jButtonAgregarProducto.doClick();
        }
    }//GEN-LAST:event_jButtonAgregarProductoKeyPressed

    private void jTextFieldCodigoPSKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldCodigoPSKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            
        }
        if (evt.getKeyCode() == KeyEvent.VK_F10) {
            jButtonGuardar.doClick();
        }
    }//GEN-LAST:event_jTextFieldCodigoPSKeyPressed

    private void jTextFieldRazonSocialKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldRazonSocialKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jTextFieldRut.requestFocus();
            jTextFieldRut.selectAll();
        }
        if (evt.getKeyCode() == KeyEvent.VK_F10) {
            jButtonGuardar.doClick();
        }
    }//GEN-LAST:event_jTextFieldRazonSocialKeyPressed

    private void jComboBoxFrecFactLecheUltraKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jComboBoxFrecFactLecheUltraKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jTextFieldLitrosDeslactosada.requestFocus();
            jTextFieldLitrosDeslactosada.selectAll();
        }
        if (evt.getKeyCode() == KeyEvent.VK_F10) {
            jButtonGuardar.doClick();
        }
    }//GEN-LAST:event_jComboBoxFrecFactLecheUltraKeyPressed

    private void jComboBoxFrecFactLecheDeslactosadaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jComboBoxFrecFactLecheDeslactosadaKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jTextFieldProductos.requestFocus();
            jTextFieldProductos.selectAll();
        }
        if (evt.getKeyCode() == KeyEvent.VK_F10) {
            jButtonGuardar.doClick();
        }
    }//GEN-LAST:event_jComboBoxFrecFactLecheDeslactosadaKeyPressed

    private void jTextFieldLitrosDeslactosadaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldLitrosDeslactosadaKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jComboBoxFrecFactLecheDeslactosada.requestFocus();
        }
        if (evt.getKeyCode() == KeyEvent.VK_F10) {
            jButtonGuardar.doClick();
        }
    }//GEN-LAST:event_jTextFieldLitrosDeslactosadaKeyPressed

    private void jListProductosKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jListProductosKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_F10) {
            jButtonGuardar.doClick();
        }
    }//GEN-LAST:event_jListProductosKeyPressed

    private int devolverIndiceReparto(Reparto reparto) {
        for (int i = 0; i < this.repartos.size(); i++) {
            Reparto r = this.repartos.get(i);
            if (r.equals(reparto)) {
                return i + 1;
            }
        }
        return 0;
    }

    private int devolverIndiceGrupoDeCliente(GrupoCliente grupoCliente) {
        for (int i = 0; i < this.grupoDeClientes.size(); i++) {
            GrupoCliente gc = this.grupoDeClientes.get(i);
            if (gc.equals(grupoCliente)) {
                return i + 1;
            }
        }
        return 0;
    }

    private void actualizarListaProductos() {
        if (cliente != null) {
            productosClienteProrrateo = cliente.getProductosClienteProrrateo();

            DefaultListModel modelo = new DefaultListModel();
            for (ProductoClienteProrrateo pcp : productosClienteProrrateo) {
                modelo.addElement(pcp);
            }

            jListProductos.setModel(modelo);
        } else {
            DefaultListModel modelo = new DefaultListModel();
            for (ProductoClienteProrrateo pcp : prodsCliNuevo) {
                modelo.addElement(pcp);
            }

            jListProductos.setModel(modelo);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IngresarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IngresarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IngresarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IngresarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                IngresarCliente dialog = new IngresarCliente(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JButton jButtonAgregarProducto;
    private javax.swing.JButton jButtonGuardar;
    private javax.swing.JButton jButtonSalir;
    private javax.swing.JComboBox<String> jComboBoxFrecFactLeche;
    private javax.swing.JComboBox<String> jComboBoxFrecFactLecheDeslactosada;
    private javax.swing.JComboBox<String> jComboBoxFrecFactLecheUltra;
    private javax.swing.JComboBox<String> jComboBoxFrecFactProductos;
    private javax.swing.JComboBox jComboBoxGruposDeClientes;
    private javax.swing.JComboBox jComboBoxReparto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelFrecFactProductos;
    private javax.swing.JLabel jLabelFrecFavtLeche;
    private javax.swing.JLabel jLabelFrecFavtLecheDeslca;
    private javax.swing.JLabel jLabelFrecFavtLecheUltra;
    private javax.swing.JLabel jLabelLitrosComun;
    private javax.swing.JLabel jLabelLitrosDeslactosada;
    private javax.swing.JLabel jLabelLitrosUltra;
    private javax.swing.JLabel jLabelProds;
    private javax.swing.JLabel jLabelProductos;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JList<String> jListProductos;
    private javax.swing.JPanel jPanelProductos;
    private javax.swing.JRadioButton jRadioButtonActivo;
    private javax.swing.JRadioButton jRadioButtonChofer;
    private javax.swing.JRadioButton jRadioButtonEmpresa;
    private javax.swing.JRadioButton jRadioButtonInActivo;
    private javax.swing.JRadioButton jRadioButtonManual;
    private javax.swing.JRadioButton jRadioButtonProrrateo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextFieldCodigoPS;
    private javax.swing.JTextField jTextFieldDireccion;
    private javax.swing.JTextField jTextFieldEmail;
    private javax.swing.JTextField jTextFieldLitrosComun;
    private javax.swing.JTextField jTextFieldLitrosDeslactosada;
    private javax.swing.JTextField jTextFieldLitrosUltra;
    private javax.swing.JTextField jTextFieldNombre;
    private javax.swing.JTextField jTextFieldProductos;
    private javax.swing.JTextField jTextFieldRazonSocial;
    private javax.swing.JTextField jTextFieldRut;
    private javax.swing.JTextField jTextFieldSucursalPS;
    private javax.swing.JTextField jTextFieldTelefono;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the accion
     */
    public String getAccion() {
        return accion;
    }

    /**
     * @param accion the accion to set
     */
    public void setAccion(String accion) {
        this.accion = accion;
    }

    /**
     * @return the cliente
     */
    public Cliente getCliente() {
        return cliente;
    }

    /**
     * @param cliente the cliente to set
     */
    public void setCliente(Cliente cliente) {
        this.cliente = cliente;
    }
}
