/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.clientes;

import ui.clientes.VentanaBuscadorClienteTodos;
import dominio.Cliente;
import dominio.Factura;
import dominio.GrupoCliente;
import java.awt.event.KeyEvent;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import sistema.SistemaInformes;
import sistema.SistemaMantenimiento;
import sistema.SistemaUsuarios;
import ui.usuarios.Constantes;
import ui.usuarios.ConsultarLogDeOperaciones;

/**
 *
 * @author Edu
 */
public class VentanaConsultaDeudaCliente extends javax.swing.JFrame {

    private Cliente cliente;
    private final List<GrupoCliente> grupoDeClientes;
    private final SistemaMantenimiento sis;
    private final SistemaInformes sisInformes;
    
    private DefaultTableModel modelo;
    private final DecimalFormat df;
    
    /**
     * Creates new form VentanaConsultaDeudaCliente
     */
    public VentanaConsultaDeudaCliente(java.awt.Frame parent, boolean modal) {
        //super(parent, modal);
        initComponents();
        sis = SistemaMantenimiento.getInstance();
        sisInformes = SistemaInformes.getInstance();
        jComboBoxGruposDeClientes.addItem("");
        grupoDeClientes = sis.devolverGrupoCliente();
        for(GrupoCliente gc : grupoDeClientes){
            jComboBoxGruposDeClientes.addItem(gc);
        }
        inicializarTablaFacturas();
        df = new DecimalFormat("0.00");
        jComboBoxGruposDeClientes.requestFocus();
    }
    
    public final void inicializarTablaFacturas() {
        modelo = new DefaultTableModel() {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        modelo.addColumn("Cliente");
        modelo.addColumn("Fecha");
        modelo.addColumn("Importe");
        jTableFacturas.setModel(modelo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabelTitulo1 = new javax.swing.JLabel();
        jRadioButtonCobraChofer = new javax.swing.JRadioButton();
        jRadioButtonCobraEmpresa = new javax.swing.JRadioButton();
        jLabelGrupoCliente = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldCliente = new javax.swing.JTextField();
        jButtonConsultar = new javax.swing.JButton();
        jButtonSalir = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabelTotal = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableFacturas = new javax.swing.JTable();
        jComboBoxGruposDeClientes = new javax.swing.JComboBox();
        jButtonRefrescar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Consulta Deuda Cliente");

        jLabelTitulo1.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabelTitulo1.setForeground(new java.awt.Color(0, 0, 255));
        jLabelTitulo1.setText("Consulta Deuda de Cliente");

        buttonGroup1.add(jRadioButtonCobraChofer);
        jRadioButtonCobraChofer.setText("Cobra Chofer");
        jRadioButtonCobraChofer.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jRadioButtonCobraChoferStateChanged(evt);
            }
        });

        buttonGroup1.add(jRadioButtonCobraEmpresa);
        jRadioButtonCobraEmpresa.setSelected(true);
        jRadioButtonCobraEmpresa.setText("Cobra Empresa");

        jLabelGrupoCliente.setText("Grupo Cliente: ");

        jLabel2.setText("Cliente:");

        jTextFieldCliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldClienteKeyPressed(evt);
            }
        });

        jButtonConsultar.setText("Consultar");
        jButtonConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConsultarActionPerformed(evt);
            }
        });
        jButtonConsultar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButtonConsultarKeyPressed(evt);
            }
        });

        jButtonSalir.setText("Salir");
        jButtonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalirActionPerformed(evt);
            }
        });
        jButtonSalir.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButtonSalirKeyPressed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 16)); // NOI18N
        jLabel1.setText("Total:");

        jLabelTotal.setFont(new java.awt.Font("Lucida Grande", 1, 16)); // NOI18N
        jLabelTotal.setText("Total");

        jTableFacturas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Cliente", "Fecha", "Importe"
            }
        ));
        jScrollPane1.setViewportView(jTableFacturas);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 392, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jComboBoxGruposDeClientes.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jComboBoxGruposDeClientesKeyPressed(evt);
            }
        });

        jButtonRefrescar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui/liquidaciones/refresh.png"))); // NOI18N
        jButtonRefrescar.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jButtonRefrescar.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        jButtonRefrescar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRefrescarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jRadioButtonCobraChofer)
                                .addGap(47, 47, 47)
                                .addComponent(jRadioButtonCobraEmpresa))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabelGrupoCliente))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextFieldCliente, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE)
                                    .addComponent(jComboBoxGruposDeClientes, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jButtonConsultar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButtonSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButtonRefrescar)
                        .addGap(70, 70, 70)
                        .addComponent(jLabelTitulo1)))
                .addContainerGap(20, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelTotal)
                .addGap(107, 107, 107))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelTitulo1)
                    .addComponent(jButtonRefrescar))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButtonCobraChofer)
                    .addComponent(jRadioButtonCobraEmpresa))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelGrupoCliente)
                    .addComponent(jButtonConsultar)
                    .addComponent(jComboBoxGruposDeClientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonSalir))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabelTotal))
                .addContainerGap(11, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButtonCobraChoferStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jRadioButtonCobraChoferStateChanged
        // TODO add your handling code here:
        if(jRadioButtonCobraChofer.isSelected()){
            jLabelGrupoCliente.setVisible(false);
            jComboBoxGruposDeClientes.setVisible(false);
            jPanel1.setVisible(false);
        } else {
            jLabelGrupoCliente.setVisible(true);
            jComboBoxGruposDeClientes.setVisible(true);
            jPanel1.setVisible(true);
            
        }
    }//GEN-LAST:event_jRadioButtonCobraChoferStateChanged

    private void jTextFieldClienteKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldClienteKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
                if ("".equals(jTextFieldCliente.getText().trim())) {
                    //Es vacio. Le habro el buscador
                    VentanaBuscadorClienteTodos vbc = new VentanaBuscadorClienteTodos(VentanaConsultaDeudaCliente.this, true);
                    vbc.setVisible(true);
                    this.cliente = vbc.getCliente();
                    jTextFieldCliente.setText(cliente.getNombre());
                    jButtonConsultar.requestFocus();
                } else {
                    //No es vacio. Busco la cadena en los rut de cliente, si conincide la muestro si no pregunto si quiere volver a ingresarlo o abrir el buscador de clientes.
                    String fraccionDelRut = jTextFieldCliente.getText().trim();
                    cliente = sis.devolverClientePorFraccionDelRut(fraccionDelRut);
                    if (cliente != null) {
                        jTextFieldCliente.setText(cliente.getNombre());
                        jButtonConsultar.requestFocus();
                    } else {
                        int resp = JOptionPane.showConfirmDialog(this, "No existe un cliente que contenga en el rut: " + fraccionDelRut + " . Desea abrir el buscador de clientes?  ", "Pregunta", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
                        if (resp == JOptionPane.YES_OPTION) {
                            VentanaBuscadorClienteTodos vbc = new VentanaBuscadorClienteTodos(VentanaConsultaDeudaCliente.this, true);
                            vbc.setVisible(true);
                            this.cliente = vbc.getCliente();
                            jTextFieldCliente.setText(cliente.getNombre());
                            jButtonConsultar.requestFocus();
                        } else if (resp == JOptionPane.NO_OPTION) {
                            jTextFieldCliente.requestFocus();
                            jTextFieldCliente.selectAll();
                        }
                    }
                }   
            
        }
    }//GEN-LAST:event_jTextFieldClienteKeyPressed

    private void jButtonSalirKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButtonSalirKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jButtonSalir.doClick();
        }
    }//GEN-LAST:event_jButtonSalirKeyPressed

    private void jButtonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalirActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButtonSalirActionPerformed

    private void jButtonConsultarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButtonConsultarKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jButtonConsultar.doClick();
        }
    }//GEN-LAST:event_jButtonConsultarKeyPressed

    private void jButtonConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConsultarActionPerformed
        // TODO add your handling code here:
        inicializarTablaFacturas();
        List<Factura> facturas;
        double totalDeuda = 0;
        try {
        if(jRadioButtonCobraEmpresa.isSelected()){
            if(jComboBoxGruposDeClientes.getSelectedIndex() == 0 && "".equals(jTextFieldCliente.getText().trim())){
                JOptionPane.showMessageDialog(this, "Debe seleccionar un cliente o un grupo de cliente para la consulta.", "Información", JOptionPane.INFORMATION_MESSAGE);
                jComboBoxGruposDeClientes.requestFocus();
            } else {
                if(jComboBoxGruposDeClientes.getSelectedIndex() !=0 && "".equals(jTextFieldCliente.getText().trim())){
                    //Busco las facturas por grupo de cliente
                    jPanel1.setVisible(true);
                    GrupoCliente gc = (GrupoCliente)jComboBoxGruposDeClientes.getSelectedItem();
                    facturas = sisInformes.devolverFacturasSinPagarPorGrupoDeCliente(gc);
                    for(Factura f : facturas){
                        cargarFactura(f);
                        totalDeuda = totalDeuda + f.getTotal();
                    }
                    jLabelTotal.setText(df.format(totalDeuda).replace(',', '.'));
                } else {
                    //Busco las facturas para el cliente
                    facturas = sisInformes.devolverFacturasSinPagarPorCliente(cliente);
                    if(facturas.isEmpty()){
                        jPanel1.setVisible(false);
                        jLabelTotal.setText(df.format(cliente.getDeuda()).replace(',', '.'));
                    } else {
                        jPanel1.setVisible(true);
                        for (Factura f : facturas) {
                            cargarFactura(f);
                            totalDeuda = totalDeuda + f.getTotal();
                        }
                        jLabelTotal.setText(df.format(totalDeuda).replace(',', '.'));
                    }
                }
            }
        } else {
            if("".equals(jTextFieldCliente.getText().trim())){
                JOptionPane.showMessageDialog(this, "Debe seleccionar un cliente para la consulta.", "Información", JOptionPane.INFORMATION_MESSAGE);
                jTextFieldCliente.requestFocus();
                jTextFieldCliente.selectAll();
            } else {
                //Busco la deuda del cliente. Por las dudas busco facturas sin pagar. Y si hay facturas sin pagar muestro la tabla, pero si no muestro solo el total que se guarda en el cliente, que puede haber sido ingresado mediante el documento Fiado Chofer
                facturas = sisInformes.devolverFacturasSinPagarPorCliente(cliente);
                if(facturas.isEmpty()){
                    jLabelTotal.setText(df.format(cliente.getDeuda()).replace(',', '.'));
                } else {
                    for (Factura f : facturas) {
                        cargarFactura(f);
                        totalDeuda = totalDeuda + f.getTotal();
                    }
                    jLabelTotal.setText(df.format(totalDeuda).replace(',', '.'));
                }
            }
        }
        } catch (Exception exp) {
            String stakTrace = util.Util.obtenerStackTraceEnString(exp);
            SistemaUsuarios.getInstance().registrarExcepcion(exp.toString(), stakTrace);
            JOptionPane.showMessageDialog(VentanaConsultaDeudaCliente.this, Constantes.MensajeDeErrorGenerico, "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButtonConsultarActionPerformed

    private void jComboBoxGruposDeClientesKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jComboBoxGruposDeClientesKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jButtonConsultar.requestFocus();
        }
    }//GEN-LAST:event_jComboBoxGruposDeClientesKeyPressed

    private void jButtonRefrescarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRefrescarActionPerformed
        // TODO add your handling code here:
        VentanaConsultaDeudaCliente vcdc = new VentanaConsultaDeudaCliente(null, false);
        vcdc.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonRefrescarActionPerformed

    public void cargarFactura(Factura f){
        Object[] object = new Object[3];
        object[0] = f.getCliente();
        SimpleDateFormat formatter;
        formatter = new SimpleDateFormat("dd-MM-yyyy");
        object[1] = formatter.format(f.getFecha());
        object[2] = df.format(f.getTotal()).replace(',', '.');
        modelo.addRow(object);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaConsultaDeudaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaConsultaDeudaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaConsultaDeudaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaConsultaDeudaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                VentanaConsultaDeudaCliente dialog = new VentanaConsultaDeudaCliente(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButtonConsultar;
    private javax.swing.JButton jButtonRefrescar;
    private javax.swing.JButton jButtonSalir;
    private javax.swing.JComboBox jComboBoxGruposDeClientes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelGrupoCliente;
    private javax.swing.JLabel jLabelTitulo1;
    private javax.swing.JLabel jLabelTotal;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButtonCobraChofer;
    private javax.swing.JRadioButton jRadioButtonCobraEmpresa;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableFacturas;
    private javax.swing.JTextField jTextFieldCliente;
    // End of variables declaration//GEN-END:variables
}
