/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.config;

import dominio.ConfiguracionFacturacion;
import javax.swing.JOptionPane;
import sistema.SistemaMantenimiento;
import sistema.SistemaUsuarios;
import ui.usuarios.Constantes;

/**
 *
 * @author Edu
 */
public class VentanaConfiguracionFacturacion extends javax.swing.JDialog {
    
    private SistemaMantenimiento sis;
    private ConfiguracionFacturacion configuracionFacturacion;
    
    
    /**
     * Creates new form VentanaConfiguracionFacturacion
     */
    public VentanaConfiguracionFacturacion(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        sis = SistemaMantenimiento.getInstance();
        jRadioButtonSoloLeche.setVisible(false);
        configuracionFacturacion = sis.devolverConfiguracionFacturacion();
        jRadioButtonModoDetallado.setSelected(configuracionFacturacion.isDetalladaPorArticulo());
        jRadioButtonModoNoDetallado.setSelected(!configuracionFacturacion.isDetalladaPorArticulo());
        jRadioButtonSoloLeche.setSelected(configuracionFacturacion.isSoloLeche());
        jRadioButtonDetalladoPorArt.setSelected(!configuracionFacturacion.isDetalladoPorGrupoDeArticulo());
        jRadioButtonDetalladoPorGrupo.setSelected(configuracionFacturacion.isDetalladoPorGrupoDeArticulo());
        jTextFieldProximoNumeroDeFactura.setText(""+configuracionFacturacion.getUltimoNumeroFactura());
        jTextFieldporcentajeFacturacion.setText("" + configuracionFacturacion.getPorcentajeFacturacion());
        jTextFieldMaximoBoletaConsumoFinal.setText("" + configuracionFacturacion.getMaximoBoletaContadoFinal());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jRadioButtonModoDetallado = new javax.swing.JRadioButton();
        jRadioButtonModoNoDetallado = new javax.swing.JRadioButton();
        jButtonGuardar = new javax.swing.JButton();
        jButtonSalir = new javax.swing.JButton();
        jRadioButtonSoloLeche = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldProximoNumeroDeFactura = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldporcentajeFacturacion = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldMaximoBoletaConsumoFinal = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jRadioButtonDetalladoPorArt = new javax.swing.JRadioButton();
        jRadioButtonDetalladoPorGrupo = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Configuración de Facturación");

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel1.setText("Configuración de Facturación");

        buttonGroup1.add(jRadioButtonModoDetallado);
        jRadioButtonModoDetallado.setSelected(true);
        jRadioButtonModoDetallado.setText("Detallado");

        buttonGroup1.add(jRadioButtonModoNoDetallado);
        jRadioButtonModoNoDetallado.setText("No Detallado ");

        jButtonGuardar.setText("Guardar");
        jButtonGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGuardarActionPerformed(evt);
            }
        });

        jButtonSalir.setText("Salir");
        jButtonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalirActionPerformed(evt);
            }
        });

        jRadioButtonSoloLeche.setText("Solo Leche");

        jLabel2.setText("Proximo Numero de Factura:");

        jTextFieldProximoNumeroDeFactura.setText("1");

        jLabel3.setText("Porcentaje de Facturación:");

        jTextFieldporcentajeFacturacion.setText("95");

        jLabel4.setText("%");

        jLabel5.setText("Maximo boleta CF:");

        buttonGroup2.add(jRadioButtonDetalladoPorArt);
        jRadioButtonDetalladoPorArt.setText("Por Artículo");

        buttonGroup2.add(jRadioButtonDetalladoPorGrupo);
        jRadioButtonDetalladoPorGrupo.setText("Por Grupo de Artículo");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(96, 96, 96)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButtonGuardar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5)
                            .addComponent(jRadioButtonSoloLeche))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldMaximoBoletaConsumoFinal)
                            .addComponent(jTextFieldProximoNumeroDeFactura)
                            .addComponent(jTextFieldporcentajeFacturacion, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jRadioButtonDetalladoPorArt)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRadioButtonDetalladoPorGrupo))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jRadioButtonModoDetallado)
                                .addGap(18, 18, 18)
                                .addComponent(jRadioButtonModoNoDetallado)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButtonModoDetallado)
                    .addComponent(jRadioButtonModoNoDetallado))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButtonDetalladoPorArt)
                    .addComponent(jRadioButtonDetalladoPorGrupo))
                .addGap(18, 18, 18)
                .addComponent(jRadioButtonSoloLeche)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldProximoNumeroDeFactura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextFieldporcentajeFacturacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldMaximoBoletaConsumoFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(jButtonGuardar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonSalir)
                .addGap(20, 20, 20))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGuardarActionPerformed
        // TODO add your handling code here:
        configuracionFacturacion.setDetalladaPorArticulo(jRadioButtonModoDetallado.isSelected());
        configuracionFacturacion.setSoloLeche(jRadioButtonSoloLeche.isSelected());
        configuracionFacturacion.setDetalladoPorGrupoDeArticulo(jRadioButtonDetalladoPorGrupo.isSelected());
        try{
            Long numFact = Long.parseLong(jTextFieldProximoNumeroDeFactura.getText().trim());
            Double porcentajeFacturacion = Double.parseDouble(jTextFieldporcentajeFacturacion.getText().trim());
            Double maximoBoletaContadoFinal = Double.parseDouble(jTextFieldMaximoBoletaConsumoFinal.getText().trim());
            configuracionFacturacion.setUltimoNumeroFactura(numFact);
            configuracionFacturacion.setPorcentajeFacturacion(porcentajeFacturacion);
            configuracionFacturacion.setMaximoBoletaContadoFinal(maximoBoletaContadoFinal);
            sis.guardarConfiguracionDeFacturacion(configuracionFacturacion);
        } catch (NumberFormatException ne){
            JOptionPane.showMessageDialog(this, "El numero y el porcentaje debe ser un numero. Tambien el maximo de una boleta de consumo final.", "Información", JOptionPane.INFORMATION_MESSAGE);
            jTextFieldProximoNumeroDeFactura.requestFocus();
            jTextFieldProximoNumeroDeFactura.selectAll();
        } catch (Exception ex) {
            String stakTrace = util.Util.obtenerStackTraceEnString(ex);
            SistemaUsuarios.getInstance().registrarExcepcion(ex.toString(), stakTrace);
            JOptionPane.showMessageDialog(this, Constantes.MensajeDeErrorGenerico, "Error", JOptionPane.ERROR_MESSAGE);
        }
        this.dispose();
    }//GEN-LAST:event_jButtonGuardarActionPerformed

    private void jButtonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalirActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButtonSalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaConfiguracionFacturacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaConfiguracionFacturacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaConfiguracionFacturacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaConfiguracionFacturacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                VentanaConfiguracionFacturacion dialog = new VentanaConfiguracionFacturacion(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton jButtonGuardar;
    private javax.swing.JButton jButtonSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JRadioButton jRadioButtonDetalladoPorArt;
    private javax.swing.JRadioButton jRadioButtonDetalladoPorGrupo;
    private javax.swing.JRadioButton jRadioButtonModoDetallado;
    private javax.swing.JRadioButton jRadioButtonModoNoDetallado;
    private javax.swing.JRadioButton jRadioButtonSoloLeche;
    private javax.swing.JTextField jTextFieldMaximoBoletaConsumoFinal;
    private javax.swing.JTextField jTextFieldProximoNumeroDeFactura;
    private javax.swing.JTextField jTextFieldporcentajeFacturacion;
    // End of variables declaration//GEN-END:variables
}
